import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "./components/Navbar"
import Footer from "./components/Footer"

export default function Home() {

  interface Features{
    title:string,
    desc:string,
    img:any
  }

  const Features:Features[] = [
    {
      title:"Share note with friends",
      desc:"Whether you have a team of 2 or 200 our share team inboxes keep everyone on the same page and one loop",
      img:"/Featured icon.png"
    },
    {
      title:"Auto completion",
      desc:"Whether you have a team of 2 or 200 our share team inboxes keep everyone on the same page and one loop",
      img:"/Featured icon (2).png"
    },
    {
      title:"Manage note with your friends",
      desc:"Whether you have a team of 2 or 200 our share team inboxes keep everyone on the same page and one loop",
      img:"/Featured icon (1).png"
    },
  ]
  return (
    <>
      <Head>
        <title>Notely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logomark.png" />
      </Head>

      <Navbar/>

      <header className="flex items-center justify-center md:mt-[100px] px-3">
        <div className='flex  justify-center md:gap-[200px] flex-col md:flex-row gap-[50px]'>
          <div className='md:w-[400px] mt-[80px] md:-ml-[100px]'>
            <h1 className='font-bold text-4xl mb-[30px]'>Enjoy note taking <br/>with your friends</h1>
            <p>Put down your thoughts in one app share with your friends and loved ones</p>

            <div></div>

          </div>
          <div className='relative ml-[50px] '>
            <div className="z-[20px]">
            <Image src="/Rectangle.png" width={250} height={300} alt="icon" />
            </div>
            <div className='z-[5px] absolute -left-[200px] top-[40px]'>
            <Image src="/74499-circle 1.png" width={350} height={300} alt="icon"/>
            </div>
           
          </div>

        </div>
      </header>



      <div className="features flex items-center justify-center mt-[100px] md:h-[400px] py-4">

        <div>
          <div className='grid grid-cols-1 md:grid-cols-3 gap-[0px]'>
            {Features.map((item:Features)=>{
              return(
                <div key={item.desc} className="w-[350px] flex flex-col items-center justify-center">
                  <div>
                  <Image src={item.img} width={50} height={50} alt="icon"/></div>
                  <div className='flex flex-col items-center justify-center'>
                    <h1 className='font-bold text-center mt-[20px] mb-[20px]'>{item.title}</h1>
                    <p className='text-sm text-center w-[280px]'>{item.desc}</p>
                  </div>

                </div>
              )
            })}
          </div>
        </div>

      </div>


      <div className='bg-black h-[400px] flex items-center justify-center text-white'>

        <div className='flex flex-col items-center gap-[30px]'>
        <Image src="/Logomark.png" width={30} height={30} alt="icon"/>
        <div>
          I use Notely for all my note taking when working on a project. I send it over to clients to crosscheck for me.
        </div>

        </div>

      </div>

      <div className="h-[250px] bg-[#F6F6F6] mt-[100px] md:w-[80%] mx-auto flex items-center justify-center rounded-md">
        <div className='flex flex-col items-center justify-center'>
          <Image src="/Avatar group.png" width={150} height={200} alt="icon"/>
          <div>
            <h2 className="font-bold mt-[20px] text-center">Do you have any questions?</h2>
            <p className='text-center'>We are available 24/7 to answer any question you have about Notely</p>
            <div className='flex items-center justify-center mt-[20px]'>
            <button className='text-white bg-black p-2 rounded-md w-[150px]'>Send a message</button>
            </div>
          </div>
        </div>

      </div>


<div className='bg-black md:h-[380px] mt-[100px]  p-4 flex  text-white overflow-y-hidden'>
  <div className=" flex justify-between w-[80%] mx-auto flex-col md:flex-row">
  

            <div className='mt-[50px]'>
                <h3>Download <span className='font-bold'>Notely</span></h3>
                <div><h1 className="md:text-5xl mt-[40px] text-4xl">Join over 2000+ users <br/>and make your life easier</h1></div>
                <div className="mt-[50px] flex gap-[20px]">
            <Image src="/Mobile app store badge.png" width={150} height={300} alt="icon" className=''/>
            <Image src="/Mobile app store badge.png" width={150} height={300} alt="icon" className=''/>
            </div>

            </div>


            <div className="mt-[25px] md:mt-0">
            <Image src="/Rectangle.png" width={300} height={300} alt="icon" className=''/>
            </div>
  </div>
</div>

<div className="mt-[100px]">
<Footer/>
</div>
     
    </>
  )
}
