import React,{useState,useEffect, useContext} from 'react'
import Image from 'next/image'
import Head from "next/head"
import Link from "next/link"
import {UserNotes} from "../services/FetchData/firestore"
import { AuthContext, AuthProvider } from '../services/Context/context'
import {getFirestore} from "firebase/firestore"
import {setDoc,doc,onSnapshot,updateDoc} from "firebase/firestore"
 import { firebaseapp } from "../Firebase/firebase";
 import {RiDeleteBinLine} from "react-icons/ri"
 import {MdOutlineAutoDelete} from "react-icons/md"
 import {AiOutlineShareAlt} from "react-icons/ai"

 import {getAuth} from  "firebase/auth";
 

function Notes() {

  type Note = {
    title:string,
    note:string
  }
  const [notes,setNotes] = useState<Array<Note>>([])
  const [loading,setLoading] = useState(false)

  const projectfirestore = getFirestore(firebaseapp)

  const {user} = useContext(AuthContext)

  const deletemovie = async (title:string)=>{
    const results = notes.filter((item:Note)=>item.title !== title)

   

    await updateDoc(doc(projectfirestore, "User", `${user?.email}`),{
      savedNotes:results
    })


  }

  const getNotes = async()=>{
    try{
await onSnapshot(doc(projectfirestore, "User", `${user?.email}`), (doc) => {
    
     setLoading(false)
      setNotes(doc.data()?.savedNotes)
    
  });
    } 
   catch(err:any){
    console.log(err.message)
  }

  }

 
  


  useEffect(()=>{
    setLoading(true)
     getNotes()
    
   
  
  },[user?.email])

  

  
  return (
   <>
    <Head>
    <title>Saved notes</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/Logomark.png" />
  </Head>

  <AuthProvider>
   <div className='h-[100vh] relative'>
    <div className='flex items-center justify-center p-3 '>
    <div className='flex flex-col items-center justify-center'>
      <div className='flex items-center justify-between w-[100%] gap-[250px] p-3 '>
        <div><Link href="/"><h1 className='font-bold text-2xl'>Notely</h1></Link></div>
        <div><Image src="/Group 3.png" width={40} height={50} alt="notesvAack"/></div>
      </div>
<br/> 
<div><input type="text" placeholder='Search' className='bg-[#D9D9D9] p-2 w-[350px] h-[40px] rounded-lg text-black focus:outline-none focus:border:none'/></div>
      <br/><br/>
<div className='grid-cols-2 grid gap-[20px]'>

  { !loading ? <div>
    {
       notes.map((note:Note)=>{
      return(
       <div className='bg-[#A692F9] text-white p-2 rounded-2xl'>
         <h1>{note?.title}</h1>
         <div>
         <p>{note?.note}</p> <MdOutlineAutoDelete onClick={()=>deletemovie(note.title)}/></div>
         </div>
      )
    })
    }
  </div>: (<div><p>Fetching Notes... Pls wait</p></div>)
   
  }
 
  
 
  
 




</div>
     
    </div>
    
   </div>
<div className="absolute bottom-0 md:left-[600px] left-[150px] flex items-center justify-center">
 <Link href="/create"> <Image src="/Group 1.png" width={100} height={50} alt="notesvAack"/></Link>
</div>
   </div>

   </AuthProvider>
   </>
  )
}

export default Notes